### ISSUE TITLE
Website gone missing? 

### ISSUE THREAD

**Issue by ebeshero** [awoods25/World-War-Project-#7]
Hey team-- We don't see anything up on your project website (http://warletters.newtfire.org/ ) any more, and you used to have a splash page up. What happened?

**Comment by ebeshero** [comment]
PS: Be sure to back up your website files here in your GitHub repo(!)

**Comment by bman8932** [comment]
The SSI stopped working (on our old HTML pages) for some reason. Alex has a better version of our webpage so I just removed our old HTML documents.

**Comment by ghbondar** [comment]
Oh, good. If @alexlavelle can push those files to GitHub, at least, that will help us.
